# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitcount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitcount.Item')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='itemview',
            index_together=set([('item', 'user_uid')]),
        ),
    ]
